plugins {
    id 'buildlogic.java-forge-conventions'
    id 'buildlogic.java-module-conventions'
}

evaluationDependsOn(':common:api')
evaluationDependsOn(':common:impl')
evaluationDependsOn(':common:mcoverlay-v1218')

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${libs.versions.forge.'1218'.get()}")
    annotationProcessor(variantOf(libs.mixin) { classifier('processor') })

    implementation project(':common:api')
    implementation project(':common:impl')
    implementation project(':common:mcoverlay-v1218')
}

jar {
    from(project(':common:api').sourceSets.main.output)
    from(project(':common:impl').sourceSets.main.output)
    from(project(':common:mcoverlay-v1218').sourceSets.main.output)
}

tasks.named('compileJava') {
    dependsOn(project(':common:mcoverlay-v1218').tasks.named('processResources'))
}
