name            = BetterUI
description     = A client-side Mixin-based mod that improves Minecraft's UI/UX.
version         = 0.1.0
id              = betterui

url             = https://github.com/ro80t/better-ui

vendor          = BetterUI Project
vendor-url      = https://github.com/ro80t

groupId         = com.ro80t.betterui
artifactId      = betterui

archiveBaseName = BetterUI
