pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases/'
        }
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        gradlePluginPortal()
    }

    includeBuild('build-logic')
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'BetterUI'

include(':common:api', ':common:impl', ':common:mcoverlay', ':common:mcoverlay-v1218')
include(
        ':fabric:common',
        ':fabric:common-legacy',
        ':fabric:common-drawcontext',
        ':fabric:common-drawcontext-v1218',
        ':fabric:1165',
        ':fabric:1182',
        ':fabric:1192',
        ':fabric:1201',
        ':fabric:1211',
        ':fabric:1214',
        ':fabric:1218'
)
include(
        ':neoforge:common',
        ':neoforge:1204',
        ':neoforge:1211',
        ':neoforge:1214',
        ':neoforge:1218',
)
include(
        ':forge:common',
        ':forge:1201',
        ':forge:1211',
        ':forge:1214',
        ':forge:1218',
)
