pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases/'
        }
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        gradlePluginPortal()
    }

    includeBuild('build-logic')
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'BetterUI'

include(':common:api', ':common:impl')
include(
        ':fabric:common',
        ':fabric:1201',
        ':fabric:1218'
)
include(
        ':neoforge:common',
)
include(
        ':forge:common',
)
