plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases/'
    }
    maven {
        name = 'MinecraftForge'
        url = 'https://maven.minecraftforge.net/'
    }
    gradlePluginPortal()
}

dependencies {
    implementation libs.neoforge.gradle
    implementation libs.fabric.loom
    implementation libs.forge.gradle
}
