plugins {
    id 'buildlogic.java-fabric-conventions'
    id 'buildlogic.java-module-conventions'
}

evaluationDependsOn(':common:api')
evaluationDependsOn(':common:impl')
evaluationDependsOn(':fabric:common')
evaluationDependsOn(':fabric:common-drawcontext')

dependencies {
    minecraft libs.minecraft.'1201'
    mappings(variantOf(libs.fabric.yarn.'1201') {
        classifier('v2')
    })
    modImplementation libs.fabric.loader.'1201'
    modImplementation libs.fabric.api.'1201'

    implementation project(':common:api')
    implementation project(':common:impl')
    implementation(project(':fabric:common')) {
        exclude group: 'net.fabricmc'
        exclude group: 'net.fabricmc.fabric-api'
    }
    implementation(project(':fabric:common-drawcontext')) {
        exclude group: 'net.fabricmc'
        exclude group: 'net.fabricmc.fabric-api'
    }
}

jar {
    from(project(':common:api').sourceSets.main.output)
    from(project(':common:impl').sourceSets.main.output)
    from(project(':fabric:common').sourceSets.main.output)
    from(project(':fabric:common-drawcontext').sourceSets.main.output)
}
