plugins {
    id 'buildlogic.java-common-conventions'

    id 'java'
    id 'jvm-test-suite'
}

testing {
    suites {
        unitTest(JvmTestSuite) {
            useJUnitJupiter()

            dependencies {
                implementation project()
            }
        }
    }
}

tasks.named('test') {
    enabled = false
}

tasks.withType(Test).configureEach {
    if (!it.enabled) {
        return
    }

    it.workingDir = new File(projectDir, "run/test/${it.name}")
    if (!it.workingDir.exists()) {
        it.workingDir.mkdirs()
    }
}

tasks.named('check') {
    dependsOn(testing.suites.unitTest)
}
