plugins {
    id 'java'
}

Properties props = new Properties()
try (FileInputStream fis = new FileInputStream(new File(parent.rootDir.getPath(), 'application.properties'))) {
    props.load(fis)
}

version = props.getProperty('version')

tasks.withType(JavaCompile).configureEach {
    configure(options) {
        encoding = 'UTF-8'
    }
}

tasks.withType(Javadoc).configureEach {
    configure(options) {
        locale = 'en_US'
        encoding = docEncoding = charSet = 'UTF-8'
    }
}

tasks.withType(AbstractCopyTask).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
