plugins {
    id 'java'
}

def javaVersion = properties.getOrDefault('java.version', 17) as int
def javaCompatSource = properties.getOrDefault('java.compatibility.source', javaVersion) as int
def javaCompatTarget = properties.getOrDefault('java.compatibility.target', javaCompatSource) as int

tasks.withType(JavaCompile).configureEach {
    it.sourceCompatibility = javaCompatSource
    it.targetCompatibility = javaCompatTarget
}

java.toolchain.languageVersion.set(JavaLanguageVersion.of(javaVersion))
