plugins {
    id 'buildlogic.java-module-conventions'
    id 'buildlogic.java-manifest-conventions'

    id 'java-library'
    id 'net.minecraftforge.gradle'
}

Properties props = new Properties()
try (FileInputStream fis = new FileInputStream(new File(parent.rootDir.getPath(), 'application.properties'))) {
    props.load(fis)
}

processResources {
    filteringCharset 'UTF-8'

    filesMatching('META-INF/mods.toml') {
        expand 'MOD_ID': props.getProperty('id'),
                'MOD_VERSION': props.getProperty('version'),
                'MOD_NAME': props.getProperty('name'),
                'MOD_DESCRIPTION': props.getProperty('description')
    }
}

tasks.named('jar', Jar) {
    manifest {
        attributes(['MixinConfigs': "${props.getProperty('id')}.mcoverlay.mixins.json"])
    }
}

minecraft {
    mappings channel: 'official', version: '1.21.8'

    runs {
        configureEach {
            workingDir.convention layout.projectDirectory.dir('run')
            args "--mixin.config=${props.getProperty('id')}.mcoverlay.mixins.json"
        }
        client {
        }
    }
}
