modLoader = "javafml"
loaderVersion = "[4,)"
license = "TODO-CHOOSE-A-LICENSE"


[[mods]]
modId = "${MOD_ID}"
version = "${MOD_VERSION}"
displayName = "${MOD_NAME}"
logoFile = "icon.png"
ordering = "NONE"
side = "CLIENT"

authors = "TODO"
description = '''${MOD_DESCRIPTION}'''


[[dependencies.${MOD_ID}]]
    modId = "neoforge"
    type = "required"
    versionRange = ">=21.8"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.${MOD_ID}]]
    modId = "minecraft"
    type = "required"
    versionRange = "=1.21.8"
    ordering = "NONE"
    side = "CLIENT"
