name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', 'gradle/libs.versions.toml') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: betterui
          path: |
            fabric/1165/build/libs/*.jar
            fabric/1182/build/libs/*.jar
            fabric/1192/build/libs/*.jar
            fabric/1201/build/libs/*.jar
            fabric/1211/build/libs/*.jar
            fabric/1214/build/libs/*.jar
            fabric/1218/build/libs/*.jar
            forge/1201/build/libs/*.jar
            forge/1211/build/libs/*.jar
            forge/1214/build/libs/*.jar
            forge/1218/build/libs/*.jar
            neoforge/1204/build/libs/*.jar
            neoforge/1211/build/libs/*.jar
            neoforge/1214/build/libs/*.jar
            neoforge/1218/build/libs/*.jar
